### ISSUE TITLE
2x client bundle size after updating to latest master

### ISSUE THREAD

**Issue by randomnerd** [jedwards1211/meteor-webpack-react#100]
without adding any new packages, client bundle size went from 360kb to 670kb... O_o
any ideas?

**Comment by jbbr** [comment]
Could you somehow figure out on which commit you have been before updating to master?

**Comment by jbbr** [comment]
BTW: What source map method are you using? (devtool in webpack config).
All 'eval' methods embeds sourcemaps in the bundle. Also source maps for npm dependencies are created by default if you include them. So adding a relatively large npm bundle might greatly increase your bundle size - at least for development.

You could try a production build and also have a look whether this might be caused by new npm depdendencies.

**Comment by randomnerd** [comment]
Oh, sorry, nevermind... I just checked file size at the wrong place... 360kb was the gzipped size, so everything is okay :S
