### ISSUE TITLE
Comparison with meteor-webpack

### ISSUE THREAD

**Issue by jperl** [jedwards1211/meteor-webpack-react#117]
Thank you for putting this example project together. It opened my eyes about what is possible and is likely going to shape the way we do meteor development.

In meteor weekly I came across https://github.com/thereactivestack/meteor-webpack -- which seems to hide some of the boilerplate. What are the benefits of using this skeleton versus https://github.com/thereactivestack/kickstart-hugeapp & vice-versa?

**Comment by ramsaylanier** [comment]
Just my opinion - I've seen both and have elected to go with this skeleton (as opposed to the meteor package) simply because I don't like that the webpack:webpack package relies on meteor related packages to work (ie the ecmascript@0.1.5). I also don't like having to define my npm dependencies inside of package.js - I'd rather have a package.json file in the root. 

I'd rather rely on babel to handle ES2015 / JSX than a meteor package (ecmascript / react packages, respectively). 

I'm sure there are better reasons for using one over the other, but there are mine.

**Comment by AdamBrodzinski** [comment]
@jperl for me this version is more like building a normal JS app and it makes the Meteor globals available to you. It also handle bundling in a way the Meteor expects. It offers the most flexibility and is the easiest to troubleshoot because 99% of all current webpack resources/tutorials apply.

However, the activestack one feels like you're getting webpack built into Meteor, which is nice for people who don't like change or are scared off by a lot of config files. Because they're hidden you'll need to learn where/what the config options are (like `webpack.packages.json`)

As far as I know they're both doing roughly the same thing under the hood.

I'm using this repo in prod in two apps and it's been working great (though my version is behind some, which is just fine). @jedwards1211 is there a better commit/branch than master-latest at the present?

**Comment by jperl** [comment]
@ramsaylanier @AdamBrodzinski thanks for the comments. We have decided to go with this approach since it provides the most flexibility and is decoupled from meteor (besides the meteor globals which can be stubbed out).

**Comment by AdamBrodzinski** [comment]
@jperl awesome! let me know if you hit any roadblocks. 
One of them might be exposing files for tests and the shell.... I ended up making a higher order function that inserts into a namespace if in devmode then passes the module through to be exported as normal. I've been meaning to add this to the wiki but have been swamped lately.

**Comment by jperl** [comment]
I will most definitely. We should do a hangout in a few weeks and share learnings. Part of the inspiration to go pure es6 / webpack is that we want to move away from velocity given the latest news that xolvio is no longer maintaining it.

**Comment by AdamBrodzinski** [comment]
Yea for sure, i'm swamped this week but may be free next week.

**Comment by jperl** [comment]
It seems that `meteor-webpack` reloads a lot quicker during development.

**Comment by AdamBrodzinski** [comment]
@jperl what are you source maps set to? For me `eval` will yield a  ~0.8 second reload while full sourcemaps will take ~2 seconds.  In a prod project it used to take 15 seconds to reload and with `eval-cheap-source-map` it's around 1 second.

https://github.com/webpack/docs/wiki/build-performance#sourcemaps

**Comment by jedwards1211** [comment]
Wow, Velocity won't be developed anymore?  That validates my efforts to do some testing without it in my own projects...when I get some spare time I should create a new version of this project with the setup I have for my own projects.  I made my unit test scripts rerun tests when webpack recompiles.  Still haven't figured out how I want to do integration testing though.

@jperl I should warn that I haven't been actively maintaining this project recently (for instance the current master's not in a great state), though it should be easier to customize than `meteor-webpack`.  I'd recommend trying the [webpack-meteor-tools](https://github.com/jedwards1211/meteor-webpack-react/tree/webpack-meteor-tools) branch right now.  Or you can use the only release in the releases section.

**Comment by jedwards1211** [comment]
@jperl Also I've never explored how to do SSR, which is something I know `meteor-webpack` does.

**Comment by jperl** [comment]
@AdamBrodzinski I was using whatever is standard in the `webpack-meteor-tools` branch when you run `node dev.json`.

Thanks @jedwards1211 for the feedback. I know I am flip-flopping, but after spending a bit more time it seems I am going to run with `meteor-webpack` since it reloads faster and looks like it might be less overhead to maintain. 

Whichever webpack pattern we use is not that important --- the important part is that we move our components to react and our logic to nicely decoupled es6 modules with minimal dependencies. Then as the landscape evolves we will reinvestigate the best pattern for webpack.

**Comment by genyded** [comment]
Not sure where you are with SSR support, but [the reactivestack](https://github.com/thereactivestack) stuff has their own SSR packge. While it works well with Meteor/React/Webpack... the SSR components actually 'hides' the `<Router>` element so trying to wrap it in a `<Provider>' is impossible making Redux a no go unless you want to manually pass store as a prop to every connect(). 

This is just something to consider when it comes to discussing SSR. The main reason I love SSR is not having to display Loading... or whatever on the initial screen.

**Comment by AdamBrodzinski** [comment]
@genyded SSR support is possible but I doubt @jedwards1211 would want to make it a default part of this boilerplate. It should be pretty easy to add it ontop of this if you're using React router. Or if you're using FlowRouter this should be a drop in once FlowRouter 4 is out.

Closing this thread as it seems to be finished off. Feel free to open an SSR issue if you'd like. I think a link in the readme to an SSR fork would be best. (keeping SSR maintained here will be a huge burden)
